stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - params.yaml
    params:
      - data_ingestion.test_size
      - data_ingestion.random_state
      - data_ingestion.numerical_cols
      - data_ingestion.categorical_cols
      - data_ingestion.input_file_path
    outs:
      - artifacts/data_ingestion/X_train.csv
      - artifacts/data_ingestion/X_test.csv
      - artifacts/data_ingestion/y_train.csv
      - artifacts/data_ingestion/y_test.csv

  data_transformation:
    cmd: python src/components/data_transformation.py
    deps:
      - src/components/data_transformation.py
      - artifacts/data_ingestion/X_train.csv
      - artifacts/data_ingestion/X_test.csv
      - artifacts/data_ingestion/y_train.csv
      - artifacts/data_ingestion/y_test.csv
    outs:
      - artifacts/data_transformation/X_train_transformed.csv
      - artifacts/data_transformation/X_test_transformed.csv
      - artifacts/data_transformation/y_train.csv
      - artifacts/data_transformation/y_test.csv
      - artifacts/data_transformation/preprocessor.pkl


  model_training:
    cmd: python src/components/model_trainer.py
    deps:
      - src/components/model_trainer.py
      - artifacts/data_transformation/X_train_transformed.csv
      - artifacts/data_transformation/X_test_transformed.csv
      - artifacts/data_transformation/y_train.csv
      - artifacts/data_transformation/y_test.csv
    outs:
      - artifacts/model/model.pkl
