data_ingestion:
  input_file_path: s3://prashant-mlops-bucket/cars24_v3.xlsx
  test_size: 0.2
  random_state: 42
  target_column: "listingPrice"
  
  numerical_cols:
    - odometer
    - fitnessAge
    - cashDownPayment
    - emiStartingValue
    - emiEndingValue
    - roiMinDiscounted
    - roiMaxDiscounted
    - roiMinOriginal
    - roiMaxOriginal
    - emiOriginalStartingValue
    - emiOriginalEndingValue
    - featureCount
    - avgEmi
  
  categorical_cols:
    - make
    - model
    - variant
    - year
    - transmissionType
    - bodyType
    - fuelType
    - ownership
    - color
    - 360DegreeCamera
    - AlloyWheels
    - AppleCarplayAndroidAuto
    - Bluetooth
    - CruiseControl
    - GpsNavigation
    - InfotainmentSystem
    - LeatherSeats
    - ParkingAssist
    - PushButtonStart
    - RearAc
    - SpecialRegNo
    - Sunroof/Moonroof
    - TopModel
    - Tpms
    - VentilatedSeats


model_training:
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2



model_evaluation:
  params:
    current_accuracy: 80