data_ingestion:
  input_file_path: s3://prashant-mlops-bucket/cars24_v3.xlsx
  test_size: 0.2
  random_state: 42
  target_column: "listingPrice"
  
  numerical_cols:
    - year
    - odometer
    - fitnessAge
    - featureCount
  categorical_cols:
    - make
    - model
    - variant
    - transmissionType
    - bodyType
    - fuelType
    - ownership
    - color



model_training:
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2

model_evaluation:
  params:
    current_accuracy: 80