name: DVC Pipeline with AWS S3

on:
  push:
    branches: [ main ]

jobs:
  dvc-pipeline:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: pip install -r requirements_dev.txt --quiet --no-cache-dir

      - name: Install DVC with S3 Support
        run: pip install 'dvc[s3]' --quiet --no-cache-dir

      - name: Pull Data from S3 (DVC)
        run: dvc pull --quiet

      - name: Reproduce DVC Pipeline
        run: dvc repro --quiet

      - name: Push Artifacts to S3 (DVC)
        run: dvc push --quiet
